name: Bug
description: Having trouble viewing the documentation?
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    label: Page URL
    description: Where did the problem occur?
    placeholder: https://craftcms.com/docs/…
    validations:
      required: true
  - type: input
    label: Client
    description: What device, operating system, and browser are you using?
  - type: markdown
    attributes:
      value: Please provide any other details that would be helpful for us to replicate the issue.
