name: Broken Link
description: Hit a 404? Report it here.
title: "[Broken Link]: "
labels: ["content"]
body:
  - type: input
    attributes:
      label: URL
      description: Location you attempted to access or where you expected a resource to be.
      placeholder: https://craftcms.com/docs/…
    validations:
      required: true
