name: Error or Omission
description: Let us know about inaccurate or missing information.
title: "[Content]: "
labels: ["content"]
assignees:
body:
  - type: dropdown
    id: product
    options:
      - Craft CMS
      - Commerce
      - Other/Multiple/Not Sure
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a problem with the documentation!

        If you encountered an incorrect or broken example, let us know where you found it. If you couldn’t find information about a topic—or the existing information didn’t answer your question—leave a brief description of what you were looking for.
