name: Error or Omission
description: Let us know about inaccurate or missing information.
title: "[Content]: "
labels: ["content"]
assignees:
body:
  - type: dropdown
    id: product
    options:
      - Craft CMS
      - Commerce
      - Other/Multiple/Not Sure
    attributes:
      label: Product
      description: Which section of the documentation are you having trouble with?
  - type: markdown
    attributes:
      label: Description
      description: If you encountered an incorrect or broken example, let us know where you found it. If you couldn’t find information about a topic—or the existing information didn’t answer your question—leave a brief description of what you were looking for.
      value: |
        ## Description

        Please provide as much detail as possible about the location of the issue and/or the problem you were trying to solve!
